from collections.abc import Callable, Sequence
from types import ModuleType, TracebackType
from typing import Any, Concatenate, Generic, ParamSpec, TypeVar, overload

_P = ParamSpec("_P")
_R = TypeVar("_R")
_F = TypeVar("_F", bound=Callable[..., Any])

class Mod:
    id: str
    module_name: str
    dependencies: tuple[str, ...]
    module: ModuleType | None
    state: str
    def __init__(self, mod_id: str, module_name: str, dependencies: tuple[str, ...] = ()) -> None: ...

class ModError(RuntimeError):
    mod_id: str
    operation: str
    def __init__(self, mod_id: str, operation: str, message: str) -> None: ...

class Registration:
    def __init__(self, close: Callable[[], None], *, owner: Mod | None = None) -> None: ...
    @property
    def closed(self) -> bool: ...
    owner: Mod | None
    def close(self) -> None: ...
    def __enter__(self) -> Registration: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, traceback: TracebackType | None) -> None: ...

class Event(Generic[_P]):
    name: str
    def __init__(self, name: str) -> None: ...
    def subscribe(self, callback: Callable[_P, None], *, priority: int = 0, owner: Mod | None = None) -> Registration: ...
    def listen(self, *, priority: int = 0, owner: Mod | None = None) -> Callable[[Callable[_P, None]], Callable[_P, None]]: ...
    def emit(self, *args: _P.args, **kwargs: _P.kwargs) -> None: ...

class HookContext(Generic[_P, _R]):
    findex: int
    def call_next(self, *args: _P.args, **kwargs: _P.kwargs) -> _R: ...
    def call_original(self, *args: _P.args, **kwargs: _P.kwargs) -> _R: ...

@overload
def hook(target: Callable[_P, _R], *, priority: int = 0, owner: Mod | None = None) -> Callable[[Callable[Concatenate[HookContext[_P, _R], _P], _R]], Callable[Concatenate[HookContext[_P, _R], _P], _R]]: ...
@overload
def hook(target: str | int | Sequence[int], *, priority: int = 0, owner: Mod | None = None) -> Callable[[_F], _F]: ...
@overload
def register_hook(target: Callable[_P, _R], callback: Callable[Concatenate[HookContext[_P, _R], _P], _R], *, priority: int = 0, owner: Mod | None = None) -> Registration: ...
@overload
def register_hook(target: str | int | Sequence[int], callback: Callable[..., Any], *, priority: int = 0, owner: Mod | None = None) -> Registration: ...

def current_mod() -> Mod | None: ...
def load_mod(mod_id: str, module_name: str, dependencies: Sequence[str] = ()) -> Mod: ...
def unload_mod(mod_id: str, *, cascade: bool = False) -> None: ...
def reload_mod(mod_id: str, *, cascade: bool = False) -> Mod: ...
def finish_loading() -> None: ...
def shutdown() -> None: ...

def load_all_stubs(base_dir: str = "./mods/stubs") -> None: ...

mods_loaded: Event[[]]
shutting_down: Event[[]]
