from collections.abc import Callable, Iterable, Iterator, MutableMapping
from typing import overload, Any, ClassVar, Generic, TypeVar
from hlmod import HlPtr

_T = TypeVar("_T")
_F = TypeVar("_F", bound=Callable[..., Any])

def hltype(idx: int) -> Callable[[type[_T]], type[_T]]: ...
def hlfunction(findex: int) -> Callable[[_F], _F]: ...

# Deliberately omit dynamic metaclass calls and attribute fallbacks. Generated
# declarations are the editor contract; runtime lookup remains native-backed.
class HlObjectMeta(type): ...

class HlObject(metaclass=HlObjectMeta):
    _hlmod_ptr: HlPtr
    _hl_type_index: ClassVar[int | HlPtr | None]
    def __init__(self) -> None: ...
    @classmethod
    def _hlmod_wrap(cls: type[_T], ptr: HlPtr) -> _T: ...

class HlVirtual:
    _hlmod_ptr: HlPtr
    def __init__(self, ptr: HlPtr) -> None: ...
    @classmethod
    def _hlmod_wrap(cls: type[_T], ptr: HlPtr) -> _T: ...

class HlCallable:
    def __init__(self, ptr: HlPtr) -> None: ...
    @property
    def ptr(self) -> int: ...
    def __call__(self, *args: Any) -> Any: ...

class HlArray(Generic[_T]):
    def __init__(self, ptr: HlPtr) -> None: ...
    @classmethod
    def create(cls, element_type_index: int, values: Iterable[_T] = ()) -> HlArray[_T]: ...
    @property
    def element_type_index(self) -> int | None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _T: ...
    def __setitem__(self, index: int, value: _T) -> None: ...
    def __iter__(self) -> Iterator[_T]: ...

class HlBytes:
    def __init__(self, pointer: HlPtr, length: int | None = None) -> None: ...
    @classmethod
    def create(cls, size: int) -> HlBytes: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> HlBytes: ...
    @property
    def capacity(self) -> int | None: ...
    def __len__(self) -> int: ...
    def read(self, offset: int = 0, length: int | None = None) -> bytes: ...
    def write(self, data: bytes | bytearray | memoryview, offset: int = 0) -> None: ...
    def decode(self, encoding: str = "utf-16-le", *, offset: int = 0, length: int | None = None) -> str: ...
    @overload
    def __getitem__(self, index: int) -> int: ...
    @overload
    def __getitem__(self, index: slice) -> bytes: ...
    def __setitem__(self, index: int | slice, value: int | bytes | bytearray | memoryview) -> None: ...

class HlEnum:
    def __init__(self, pointer: HlPtr) -> None: ...
    @property
    def type_index(self) -> int | None: ...
    @property
    def constructor_index(self) -> int: ...
    @property
    def constructor_name(self) -> str: ...
    @property
    def parameters(self) -> tuple[Any, ...]: ...
    @classmethod
    def create(cls, type_index: int, constructor: str | int, *parameters: Any) -> HlEnum: ...

class HlDynObject(MutableMapping[str, Any]):
    def __init__(self, pointer: HlPtr | None = None) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __dir__(self) -> list[str]: ...

class HlRef(Generic[_T]):
    def __init__(self, pointer: HlPtr) -> None: ...
    @property
    def value(self) -> _T: ...
    @value.setter
    def value(self, value: _T) -> None: ...
    @property
    def element_type_index(self) -> int | None: ...
    @classmethod
    def create(cls, type_index: int, value: _T) -> HlRef[_T]: ...

def inspect_native(value: object | int) -> dict[str, Any]: ...
